Update mac-build.yml
Don't cancel for X11
Try to detect test failures better

diff --git a/.github/workflows/mac-build.yml b/.github/workflows/mac-build.yml
--- a/.github/workflows/mac-build.yml
+++ b/.github/workflows/mac-build.yml
@@ -39,7 +39,11 @@ jobs:
           }
       - name: Run Tests
         run: |
-          make test styles=develop || {
+          make test styles=develop | tee out-tests.txt || {
+            echo "::error::Failure during Test"
+            exit 1
+          }
+          cat out-tests.txt | grep -q "Failed[[:space:]][[:space:]]*[1-9]" && {
             echo "::error::Failure during Test"
             exit 1
           }
@@ -60,6 +64,8 @@ jobs:
           - symbols: "no"
             options: "--disable-aqua"
             install_x11: 1
+    # Mark the X11 build as non-critical
+    continue-on-error: ${{ matrix.install_x11 }}
     defaults:
       run:
         shell: bash
@@ -122,7 +128,11 @@ jobs:
           }
       - name: Run Tests
         run: |
-          make test || {
+          make test | tee out-tests.txt || {
+            echo "::error::Failure during Test"
+            exit 1
+          }
+          cat out-tests.txt | grep -q "Failed[[:space:]][[:space:]]*[1-9]" && {
             echo "::error::Failure during Test"
             exit 1
           }
