Update mac-build.yml

diff --git a/.github/workflows/mac-build.yml b/.github/workflows/mac-build.yml
--- a/.github/workflows/mac-build.yml
+++ b/.github/workflows/mac-build.yml
@@ -1,4 +1,4 @@
-name: macOS Build and Test
+name: macOS
 on: [push]
 env:
   ERROR_ON_FAILURES: 1
@@ -8,13 +8,24 @@ jobs:
     defaults:
       run:
         shell: bash
-        working-directory: macosx
+        working-directory: tk/macosx
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+        with:
+          path: tk
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          repository: tcltk/tcl
+          ref: core-8-branch
+          path: tcl
       - name: Prepare
-        run: touch tkStubInit.c
-        working-directory: generic
+        run: |
+          touch tk/generic/tkStubInit.c
+          mkdir build
+          echo "BUILD_DIR=`cd build && pwd`" >> $GITHUB_ENV
+        working-directory: .
       - name: Build
         run: make all
       - name: Run Tests
@@ -28,22 +39,46 @@ jobs:
         symbols:
           - "no"
           - "mem"
-        dtrace:
-          - "no"
-          - "yes"
     defaults:
       run:
         shell: bash
-        working-directory: unix
+        working-directory: tk/unix
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+        with:
+          path: tk
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          repository: tcltk/tcl
+          ref: core-8-branch
+          path: tcl
       - name: Prepare
         run: |
           touch tkStubInit.c
           mkdir "$HOME/install dir"
-        working-directory: generic
-      - name: Configure (symbols=${{ matrix.symbols }} dtrace=${{ matrix.dtrace }})
+        working-directory: tk/generic
+      - name: Build Tcl
+        # Note that macOS is always a 64 bit platform
+        run: |
+          ./configure --enable-64bit ${CFGOPT} "--prefix=$HOME/install dir" || {
+            cat config.log
+            echo "::error::Failure during Tcl Configure"
+            exit 1
+          }
+          make all || {
+            echo "::error::Failure during Tcl Build"
+            exit 1
+          }
+          make install || {
+            echo "::error::Failure during Tcl Install"
+            exit 1
+          }
+        working-directory: tcl/unix
+        env:
+          CFGOPT: --enable-symbols=${{ matrix.symbols }}
+      - name: Configure (symbols=${{ matrix.symbols }}
         # Note that macOS is always a 64 bit platform
         run: |
           ./configure --enable-64bit ${CFGOPT} "--prefix=$HOME/install dir" || {
@@ -52,7 +87,7 @@ jobs:
             exit 1
           }
         env:
-          CFGOPT: --enable-symbols=${{ matrix.symbols }} --enable-dtrace=${{ matrix.dtrace }}
+          CFGOPT: --enable-symbols=${{ matrix.symbols }}
       - name: Build
         run: |
           make all tktest || {
