Update win-build.yml
Better test failure detection

diff --git a/.github/workflows/win-build.yml b/.github/workflows/win-build.yml
--- a/.github/workflows/win-build.yml
+++ b/.github/workflows/win-build.yml
@@ -103,7 +103,15 @@ jobs:
           }
       - name: Run Tests
         run: |
-          make test || {
+          make test-classic | tee out-classic.txt || {
+            echo "::error::Failure during Test"
+            exit 1
+          }
+          make test-ttk | tee out-ttk.txt || {
+            echo "::error::Failure during Test"
+            exit 1
+          }
+          cat out-classic.txt out-ttk.txt | grep -q "Failed     [1-9]" && {
             echo "::error::Failure during Test"
             exit 1
           }
